name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  url: 
    required: true
    description: 'A valid Dynatrace URL'
  token:
    required: true
    description: 'A valid Dynatrace API-token'
runs:
  using: 'node12'
  main: 'dist/index.js'
